name: create_social
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cupertino_icons: ^1.0.5
  cloud_firestore: ^3.2.1
  cloud_functions: ^3.3.1
  firebase_storage: ^10.3.1
  firebase_messaging: ^11.4.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true

